server:
  port: 8080

spring:
  application:
    name: mini-cdc-sync
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:192.168.100.128:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: mini-cdc-redis-consumer
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false
      auto-startup: ${mini-cdc.enabled:false}
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: ${REDIS_TIMEOUT:5s}

mini-cdc:
  enabled: true
  log-event-json: true
  mysql:
    host: ${CDC_MYSQL_HOST:127.0.0.1}
    port: ${CDC_MYSQL_PORT:3306}
    username: ${CDC_MYSQL_USERNAME:}
    password: ${CDC_MYSQL_PASSWORD:}
    database: ${CDC_MYSQL_DATABASE:mini}
    table: ${CDC_MYSQL_TABLE:user}
    jdbc-url: ${CDC_MYSQL_JDBC_URL:jdbc:mysql://127.0.0.1:3306/mini?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}

  kafka:
    topic: user-change-topic
  redis:
    key-prefix: "user:"

logging:
  level:
    com.yunye.mncdc: info
    org.apache.kafka.clients.consumer.ConsumerConfig: warn
